[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "0.5"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
